### PR TITLE
Change SWIG depends to build_depend

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Review by gavanderhoorn — APPROVED** [review]
Approving with the comment that I'm not sure whether these are really not used at runtime.

Yacc and Bison and automake I'm pretty sure of (they are build tools and parsers/tokenizers) and `pcre` would also make sense as just a build dependency, but I haven't checked.

**Comment by Levi-Armstrong** [comment]
@johnwason Do you know if `pcre` is only a build_depend?

**Comment by johnwason** [comment]
PCRE is a runtime dependency as well.

**Comment by Levi-Armstrong** [comment]
Thank you @gavanderhoorn and @johnwason !

**Pull request merged**
