### PR TITLE
Add Google Benchmark

### PR DESCRIPTION
**Pull request by mpowelson**
Adds [Google Benchmark](https://github.com/google/benchmark) for benchmarking key functions

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
:+1: for benchmarking, but could this please not be called `Benchmark`? That's a bit too generic -- and is already colliding with another poorly named package in my workspace ;)

**Comment by mpowelson** [comment]
Sure. How's google_benchmark?

**Comment by gavanderhoorn** [comment]
Yes, much better.

Also seems to align somewhat better with [REP-144](https://www.ros.org/reps/rep-0144.html).

**Comment by Levi-Armstrong** [comment]
I have been using the package name defined in rosdep key so things get built in the correct order. Does a key exist for google benchmark?

**Comment by gavanderhoorn** [comment]
That would of course always be preferable.

**Comment by Levi-Armstrong** [comment]
Well it looks like the rosdep key is `benchmark` shown [here](https://github.com/ros/rosdistro/blob/1def2fbe51e8345baf2b8dd757f5661eec7cd4d3/rosdep/base.yaml#L229). Thoughts?

**Comment by mpowelson** [comment]
I didn't realize there was a debian. It would seem that we don't need this in that case.

**Comment by Levi-Armstrong** [comment]
Good point!

**Comment by gavanderhoorn** [comment]
Wow, what a terrible name for a package.

Leave it to google to claim a regular noun for a C++ library name.

But yeah: if there is a binary and it's recent enough, it should be used.

**Pull request closed without merging**
