### PR TITLE
Add OMPL as an optional package

### PR DESCRIPTION
**Pull request by mpowelson**
I thought I would see if there was interest in adding this since I already had it. I had to build OMPL from source because of [this issue on 1.4.2](https://github.com/ompl/ompl/issues/664). This PR adds it as an optional dependency like Eigen or KDL.

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
Sound good to me. Once CI is passing we can merge it.

**Comment by mpowelson** [comment]
@Levi-Armstrong It looks like it can't find boost. I had copied it from the orocos_kdl package, but I switched it to be more like the bullet one building in ompl-build. I don't know why that would prevent it from finding boost though.

**Comment by Levi-Armstrong** [comment]
try adding boost rosdep key to the package.xml. It may not be installed.

**Comment by mpowelson** [comment]
Interestingly, I just noticed that they added a package.xml to master. It just isn't in 1.4.2.

**Comment by Levi-Armstrong** [comment]
If you pass -D_USE_MATH_DEFINES=ON it will then find M_PI.

**Comment by Levi-Armstrong** [comment]
Only needed for windows build.

**Comment by mpowelson** [comment]
@Levi-Armstrong Did I not do it correctly?

**Comment by Levi-Armstrong** [comment]
It may be missing a header also. I disabled the build of the demo to see if that is the only location they are used.

**Comment by mpowelson** [comment]
Looks like that did it

**Comment by mpowelson** [comment]
@Levi-Armstrong

**Pull request merged**
